//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.30 at 10:35:43 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:9091/types/SendEmailInput", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.notes.soap.mailSender;
